[build]
  # Frontend build command
  command = "npm run build"
  # Frontend build output directory
  publish = "dist"
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirect all API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Environment variables will be set in Netlify dashboard